 <div class="field">
                    /* class="required" means 'Company' field is required to register */
                    <label for="company" class="required">  <em>*</em>

                      <?php echo $this->__('Company') ?>

                    </label>

                    <div class="input-box">

                      <input type="text" name="company" id="company" value=""<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?> required-entry" />

                    </div>

 </div>



